# .coderabbit.yaml
language: "ko-KR"
early_access: false
reviews:
  profile: "balanced"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  exclude:
    - "**/*.md"
    - "docs/**"
    - "build/**"
    - "generated/**"
  domain_knowledge:
    backend: true
    frontend: true
chat:
  auto_reply: true