# .coderabbit.yaml
language: "ko-KR"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!**/*.md"
    - "!docs/**"
    - "!build/**"
    - "!generated/**"
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true