-- V1: 기본 테이블 생성 (H2 Database)

CREATE SCHEMA IF NOT EXISTS yachaerang;
SET SCHEMA yachaerang;

-- 1. member table
CREATE TABLE IF NOT EXISTS member (
                                      member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR(50) NOT NULL,
    nickname VARCHAR(50),
    email VARCHAR(100) NOT NULL,
    member_code VARCHAR(200) NOT NULL,
    member_status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    member_role VARCHAR(15) NOT NULL DEFAULT 'ROLE_USER',
    password VARCHAR(500),
    image_url VARCHAR(500),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    inactivated_at TIMESTAMP,

    CONSTRAINT uq_member_email UNIQUE (email),
    CONSTRAINT uq_member_code UNIQUE (member_code),

    CONSTRAINT chk_member_status_type
    CHECK (member_status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_role_type
    CHECK (member_role IN ('ROLE_ANONYMOUS', 'ROLE_USER', 'ROLE_ADMIN'))
    );

CREATE INDEX IF NOT EXISTS idx_member_email ON member(email);
CREATE INDEX IF NOT EXISTS idx_member_code ON member(member_code);

-- 2. farm table
CREATE TABLE IF NOT EXISTS farm (
                                    farm_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    member_id BIGINT NOT NULL,

                                    manpower INT,
                                    location VARCHAR(255),
    cultivated_area DECIMAL(15, 2),
    flat_area DECIMAL(15, 2),
    main_crop VARCHAR(100),
    grade VARCHAR(5),
    comment VARCHAR(50),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_farm_member
    FOREIGN KEY (member_id)
    REFERENCES member(member_id)
    ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_farm_member_id ON farm(member_id);

-- 3. bot_session table
CREATE TABLE IF NOT EXISTS bot_session (
                                           bot_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           member_id BIGINT NOT NULL,
                                           started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                           updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                           CONSTRAINT fk_bot_session_member
                                           FOREIGN KEY (member_id)
    REFERENCES member(member_id)
    ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_bot_session_member_id ON bot_session(member_id);
CREATE INDEX IF NOT EXISTS idx_bot_session_started_at ON bot_session(started_at);

-- 4. bot_message table
CREATE TABLE IF NOT EXISTS bot_message (
                                           bot_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           sender_id BIGINT NOT NULL,
                                           content CLOB NOT NULL,
                                           bot_session_id BIGINT NOT NULL,

                                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                           updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                           CONSTRAINT fk_bot_message_sender
                                           FOREIGN KEY (sender_id) REFERENCES member(member_id)
    ON DELETE CASCADE,

    CONSTRAINT fk_bot_message_bot_session
    FOREIGN KEY (bot_session_id) REFERENCES bot_session(bot_session_id)
    ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_bot_message_sender_id ON bot_message(sender_id);
CREATE INDEX IF NOT EXISTS idx_bot_message_bot_session_id ON bot_message(bot_session_id);

-- 5. product 테이블
CREATE TABLE IF NOT EXISTS product (
                                       product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       name VARCHAR(200) NOT NULL,
    product_code VARCHAR(100) NOT NULL,

    item_name VARCHAR(50),
    item_code VARCHAR(50),
    kind_name VARCHAR(50),
    kind_code VARCHAR(50),
    product_rank VARCHAR(50),
    rank_code VARCHAR(50),
    unit VARCHAR(50),
    origin VARCHAR(100),
    image_url VARCHAR(500),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_product_code UNIQUE (product_code)
    );

CREATE INDEX IF NOT EXISTS idx_product_code ON product(product_code);

-- 6. article table
CREATE TABLE IF NOT EXISTS article (
    article_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    content CLOB NOT NULL,
    image_url VARCHAR(500),
    url VARCHAR(500),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- 7. tag table
CREATE TABLE IF NOT EXISTS tag (
    tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    article_id BIGINT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tag_article
    FOREIGN KEY (article_id)
    REFERENCES article(article_id)
    ON DELETE CASCADE
    );

-- 8. favorite table
CREATE TABLE IF NOT EXISTS favorite (
    favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    product_code VARCHAR(100) NOT NULL,
    period_type VARCHAR(50) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_favorite_member
    FOREIGN KEY (member_id)
    REFERENCES member(member_id)
    ON DELETE CASCADE,
    CONSTRAINT fk_favorite_product
    FOREIGN KEY (product_code)
    REFERENCES product(product_code)
    ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_favorite_member_id ON favorite(member_id);
CREATE INDEX IF NOT EXISTS idx_favorite_product_code ON favorite(product_code);

-- 9. daily_price table
CREATE TABLE IF NOT EXISTS daily_price (
                                           daily_price_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           price_date DATE NOT NULL,
                                           price DECIMAL(15, 2) NOT NULL,
    product_code VARCHAR(100) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_daily_product_product
    FOREIGN KEY (product_code)
    REFERENCES product(product_code)
    ON DELETE CASCADE,

    CONSTRAINT uk_daily_product_product_date UNIQUE (product_code, price_date)
    );

CREATE INDEX IF NOT EXISTS idx_daily_product_product_code ON daily_price(product_code);
CREATE INDEX IF NOT EXISTS idx_daily_product_price_date ON daily_price(price_date);

-- 10. weekly_price table
CREATE TABLE IF NOT EXISTS weekly_price (
                                            weekly_price_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            product_code VARCHAR(100) NOT NULL,
    price_year INT NOT NULL,
    week_number INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    avg_price DECIMAL(15, 2),
    max_price DECIMAL(15, 0),
    min_price DECIMAL(15, 0),
    price_count INT DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_weekly_product_product
    FOREIGN KEY (product_code)
    REFERENCES product(product_code)
    ON DELETE CASCADE,

    CONSTRAINT uk_weekly_product_product_week UNIQUE (product_code, start_date)
    );

CREATE INDEX IF NOT EXISTS idx_weekly_product_product_code ON weekly_price(product_code);
CREATE INDEX IF NOT EXISTS idx_weekly_product_week_start ON weekly_price(start_date);

-- 11. monthly_price table
CREATE TABLE IF NOT EXISTS monthly_price (
                                             monthly_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             product_code VARCHAR(100) NOT NULL,
    price_year INT,
    price_month INT,
    avg_price DECIMAL(15, 2),
    min_price DECIMAL(15, 0),
    max_price DECIMAL(15, 0),
    price_count INT DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_monthly_product_product
    FOREIGN KEY (product_code)
    REFERENCES product(product_code)
    ON DELETE CASCADE,

    CONSTRAINT uk_monthly_product_product_month UNIQUE (product_code, price_year, price_month)
    );

CREATE INDEX IF NOT EXISTS idx_monthly_product_month ON monthly_price(price_year, price_month);

-- 12. yearly_price table
CREATE TABLE IF NOT EXISTS yearly_price (
                                            yearly_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            product_code VARCHAR(100) NOT NULL,
    price_year INT,
    avg_price DECIMAL(15, 2),
    min_price DECIMAL(15, 0),
    max_price DECIMAL(15, 0),
    start_price DECIMAL(15, 0),
    end_price DECIMAL(15, 0),
    price_count INT DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_yearly_price_product
    FOREIGN KEY (product_code)
    REFERENCES product(product_code)
    ON DELETE CASCADE,

    CONSTRAINT uk_yearly_price UNIQUE (product_code, price_year)
    );

CREATE INDEX IF NOT EXISTS idx_year ON yearly_price(price_year);