DROP TABLE IF EXISTS tag CASCADE;
DROP TABLE IF EXISTS article CASCADE;
DROP TABLE IF EXISTS monthly_product CASCADE;
DROP TABLE IF EXISTS yearly_price CASCADE;
DROP TABLE IF EXISTS member_product CASCADE;
DROP TABLE IF EXISTS daily_product CASCADE;
DROP TABLE IF EXISTS weekly_product CASCADE;
DROP TABLE IF EXISTS product CASCADE;